server:
  port: 9099

spring:
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    username: dev
    password: password
    url: jdbc:postgresql://localhost:5434/providers?currentSchema=public
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true